### ISSUE TITLE
Maak korte metten met het Angelsaksische gebral

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#101]
Zeg makker, bent gij niet vereerd om in ons prachtige koninkrijk te teren?
Wij, de compagnie van Nederlandsche Specerijen en vrinden, zouden graag zien dat uw machine, 'DankTimesBot', zich aanpast aan de hedendaagse Nederlandsche Normen en Waarden. 

Ik stel u voor, kompaan, om te beginnen door de naam te veranderen naar 'VochtigeTijdenMachine'. Wellicht een nadruk op de juiste karakters, `VOChtigeTijdenMachine`. 
Het 'LeaderBoard' is gebral, daar wilt u ten zeerste vanaf. Wellicht staat een `Leiderbord` beter op uw naam.

**Comment by Agadar** [comment]
Seeing as we're not going to introduce localizations anytime soon, I'm closing this for now.
