### ISSUE TITLE
Multiplayer penalty

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#102]
It happens a lot that people tag each other to notify them of a danktime. This should be penalized so the a players score shows how good they are at getting points. Not how good they are at getting carried.
Penalty options:

- Lose an X amount of point for each person you tag.
- Get no points for that specific danktime.

**Comment by Agadar** [comment]
It would be a challenge to differentiate 'normal' tags from these 'carry' tags you speak of, and I don't particularly agree we should punish such acts of brotherly love.
