### ISSUE TITLE
Support dynamic loading of plugins

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#110]
At this moment, if you want to load a new plugin into DankTimesBot, you have to resort to a reboot. 
This has various implications, for instance that the surprise dank times will be rescheduled, and that the bot has to be down for some time (inbetween shutdown and boot).

It would be more convenient if there was some way to add / remove plugins during runtime, perhaps through a CLI.

**Comment by Agadar** [comment]
This is entirely possible, but I predict quite a bit of rework and new work will have to be done in order to implement this properly. I encourage you to propose a design and fork the repo to make your dreams come true.

**Comment by Agadar** [comment]
No design ever forwarded, so closing for now.
