### ISSUE TITLE
Allow Plugins to compose their own messages

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#112]
Right now, plugins can only return a `string` from commands. It would be nice if bots could return an entire Message object, which is then dispatched by the DankTimesBot core. This would help because bots could have more control over their messages, and for example turn off notifications or reply to specific commands.

**Comment by Agadar** [comment]
This idea has merit. I invite you to draft a possible design for this.

**Comment by Agadar** [comment]
No design ever submitted so closing for now.
