### ISSUE TITLE
Offer a way for plugins to provide command aliases

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#114]
Currently, the bot allows for plugins to define commands with a 1 word 'trigger' -  while this works for most cases, there are also cases where it could be beneficial to have aliases if the command is otherwise hard (or too long) to type.

I propose to add a field to the BotCommand class such that any command can have one or more aliases. 

With aliases, the risk of plugin command naming conflicts increases. Perhaps the bot should show an error message if multiple plugins are proposing the same commands / aliases.

**Comment by Agadar** [comment]
Fixed in 05f59289eaac34782b15bac0e57e968bf4a07da4. Commands now take names string array instead of single name string. Name at index 0 is considered the primary one.

DankTimesBot already throws an error at launch if an attempt is made to register commands with the same name(s).
