### ISSUE TITLE
Ignore scheduled messages

### ISSUE THREAD

**Issue by Agadar** [Agadar/DankTimesBot#126]
Message class should expose a flag we can check: https://core.telegram.org/constructor/message

Scheduling messages for dank times and other stuff is against the spirit of the bot and thus should be ignored.

**Comment by Lerke** [comment]
Maybe add an additional setting for a punishment. Straight up remove 10% of someone's dank time points when they cheat

**Comment by Agadar** [comment]
Punishing them as well seems a bit petty.

**Comment by Lerke** [comment]
Telegram HTTP API which `node-telegram-bot-api` seems to use doesn't seem to have a flag for whether a message was scheduled or not.

**Comment by Corpelijn** [comment]
> Telegram HTTP API which `node-telegram-bot-api` seems to use doesn't seem to have a flag for whether a message was scheduled or not.

yes it does
from_scheduled 	flags.18?true 	Whether this is a scheduled message

**Comment by Lerke** [comment]
@Corpelijn The protocol supports it, but our library doesn't seem to track this property as of now. Check: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-telegram-bot-api/index.d.ts#L447

**Comment by Agadar** [comment]
Telegram Bot API doesn't support this right now. Created a feature request on the official repository. See https://github.com/tdlib/telegram-bot-api/issues/246.

**Comment by Agadar** [comment]
Unfortunately this is not possible because the Telegram backend does not support this field after all. See conclusion to previously mentioned issue.
