### ISSUE TITLE
Patchnotes message

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#13]
Send a patch notes message to the chats using DankTimesBot. This way everyone knows when a new update becomes active and what is new in the DankTimesWorld

**Comment by Lerke** [comment]
Good idea. Needs a technical specification: Where will we save this changelog. Will it contain the info of every version or just the current one? Should the CI not deploy new builds when the changelog is unaltered? @Agadar

**Comment by Agadar** [comment]
Considering settings and data are already json files, it would be consistent to make the changelog a json file as well. It would also be saved in the same folder, and would contain the info of every version. The `/changelog` command would only show the info of the latest version.

As for the CI not deploying new builds when the changelog is unaltered, we'll need Nick's expertise on this to see whether such a thing is even possible.

**Comment by Agadar** [comment]
Implemented since 3641732954651a28be2a85b73f2b59db14eaff3b.
