### ISSUE TITLE
Some users do not have a username and are not shown in messages

### ISSUE THREAD

**Issue by Corpelijn** [Agadar/DankTimesBot#150]
![image](https://user-images.githubusercontent.com/10760016/177525594-3d47c9a2-76d5-42c3-9f71-2b834c7eec8f.png)

**Comment by Agadar** [comment]
That's because he did not have a username set. I'd've expected the message to have shown 'anonymous', though.

**Comment by Agadar** [comment]
Closing this for now as we haven't seen this happen again since then. Reopen or make new issue if it happens again.
