### ISSUE TITLE
Add /remindme command

### ISSUE THREAD

**Issue by Agadar** [Agadar/DankTimesBot#160]
e.g. '/remindme 15 Kill Miako' would schedule a reminder 15 minutes from now. When the time comes, the bot tags the user that gave the command with the supplied text, e.g. '@Marton Kill Miako'.

**Comment by Lerke** [comment]
https://github.com/Lerke/DankTimesBot-Plugin-RemindMe

**Comment by Agadar** [comment]
Implemented by Lerke as a plugin so closing.
