### ISSUE TITLE
CRON reached maximum iterations

### ISSUE THREAD

**Issue by Corpelijn** [Agadar/DankTimesBot#161]
While testing a new plugin my local instance of DankTimesBot crashed with the following error message:
Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0 * * * * - UTC offset: +00:00 - current Date: Sun Jan 14 2024 20:00:09 GMT+0100

Searching the GitHub of the cron library, I found this issue that mentions that v1 is old and might have some issues (https://github.com/kelektiv/node-cron/issues/816).
DankTimesBot also uses v1 of cron.js (v1.8.2). Please update the cron.js library.

**Comment by Agadar** [comment]
Closed due to lack of feedback (through other channels).
