### ISSUE TITLE
Introduce immutable PreUserScoreChangedEventArguments

### ISSUE THREAD

**Issue by Agadar** [Agadar/DankTimesBot#162]
Add field to PreUserScoreChangedEventArguments that makes its value immutable so that plugins can't accidentally mess things up for point assignments that shouldn't really ever be changed, only observed, such as /donate.

**Comment by Lerke** [comment]
This should probably be done for all Plugin events. Plugins shouldn't write any objects held by DTB directly, but only do so via the appropriate interfaces
