### ISSUE TITLE
Indication when you move up or down on the leaderboard

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#19]
Arrows before the names on the leaderboard which indicate if the user has moved up, down or stayed at the same spot on the leaderboard since the last time the leaderboard was shown.

Emoji's: ⬆️⬇️🔼🔽⏫⏬
or ascii character: ↑ ↓⇑ ⇓🡑 🡓🡡 🡣🡩 🡫🡱 🡳 🡹 🡻🢁 🢃⤊ ⤋

**Comment by Lerke** [comment]
Good idea. Optionally include a little +1/+2/+n or -1/-2/-n to indicate how many positions the player moved since last leaderboard.

**Comment by Agadar** [comment]
Implemented since 7c58bde98caf93513bc73bac6d95875f73b5a5c5. Style of the arrow emoji's will stay the same or change depending on user feedback.
