### ISSUE TITLE
Remove case sensitivity 

### ISSUE THREAD

**Issue by pommeldier** [Agadar/DankTimesBot#23]
Mobile devices normally start with a capital letter by default and requires adjustment from the user. Leaving this responsibility with the user creates problems with the fairness of the game, because the users are not aware of this problem by default.

**Comment by Agadar** [comment]
Agreed. Scheduled for v.1.1.0, assuming no disagreement from other contributors.

**Comment by Agadar** [comment]
Implemented in 6436c591745309b215d4fab30792e32838f9403c.
