### ISSUE TITLE
Print the username of the player that scored first

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#44]
If you're being competitive, it's nice to see which player scored first on a dank time.

**Comment by Agadar** [comment]
You mean showing it on the leaderboard who was first?

**Comment by bart-kneepkens** [comment]
Showing the leaderboard might be a bit much. What you would want to do is highlight the player who scored first.

**Comment by Agadar** [comment]
Highlight on the leaderboard that is posted after every dank time, or highlight in some other way?

**Comment by bart-kneepkens** [comment]
It would be cool if the bot could send a message explicitly stating the first player.

For example:
`**LEET**: Agadar was first!'

**Comment by Agadar** [comment]
But you already see who is first, no? It's the guy who, well, was the first to post the time.

**Comment by bart-kneepkens** [comment]
Synchronization issues make the fact that not all clients might receive all the messages in the correct order. Also, a valid 'dank time' posted at 16:20:00 exactly, might look like 16:19:58 on some clients. There is no way to really see who came first, other than to wait for the leaderboard.

**Comment by Agadar** [comment]
Good points. I'll schedule it for v.1.2.0 and plan a command along the lines of a `/togglefirstnotifications` with which this setting can be enabled or disabled.

**Comment by Agadar** [comment]
Implemented since 008d96658ad69388a4e55e70223c548f65c674da.
