### ISSUE TITLE
Daily, weekly, monthly and yearly leaderboards.

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#53]
At the end of the day, week, month and/or year send a message containing information about how many points everyone has made in that timeframe.

--- LEADERBOARD 12 AUG ---

1.    Person1 50
2.    Person2 25
3.    Person3 10

**Comment by Agadar** [comment]
Sounds like fun, but I'll leave it to others to implement this as I would like to move to other projects myself.

**Comment by Lerke** [comment]
This will most likely be delegated to some plugin soon-ish.

**Comment by Agadar** [comment]
Seeing as the intention is to move this to a plugin, I will close this.

**Comment by Lerke** [comment]
Plugin repo is found [here](https://github.com/Lerke/DankTimesBot-Plugin-Extended-Leaderboards). Feel free to dump issues there.
