### ISSUE TITLE
Surprise danktimes formatting problem

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#57]
The danktimesbot send out the following message: Surprise dank time! Type '13 }' for points!
None of these responses gave us points: 13}, 1302, 132

![image](https://user-images.githubusercontent.com/21357422/29313459-689ff4ec-81ba-11e7-9ca5-622b8b8abfb4.png)

**Comment by Agadar** [comment]
Fixed since 2a176d7544e63d61d7b132e54a7421bd4b782342.
