### ISSUE TITLE
Modify leaderboard from plugin

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#60]
@Lerke My new plugin would benefit from this feature.
If I could add lines at a specific location in the leaderboard I wouldn't have to create new messages.
This way we prevent spamming chats.

**Comment by Lerke** [comment]
This issue is no longer needed. Plugins can get an actual leaderboard with Chat Services implemented in #61. By design, plugins won't be able to modify a chat its data.
