### ISSUE TITLE
Share data with plugins.

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#61]
@Lerke 
Allow a plugin to read or otherwise request the data for a specific chat. 
This way a plugin can respond to a persons score.

**Comment by MaikoKingma** [comment]
Also include a groupID and senderID in plugin event arguments so a plugin can retrieve data necessary to process a plugin event.

**Comment by Agadar** [comment]
Needs refinement: exactly what data should be accessible from chats via the plugin API?

**Comment by Lerke** [comment]
Plugins now have Chat Services. See a590b15b0a2440bcf4c6f75def28367d89805050 & ` src/plugin-host/plugin-chat-services/chat-services.ts`
