### ISSUE TITLE
Bug when starting the bot on windows

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#62]
When starting the bot on windows an error is returned because the linux command ```rm``` is used. 
This is simply fixed if the user removes the clean script and all references to the clean script.
(```package.json``` line 7,8 & 9)

Maybe you can change the file to support windows or mention this fix in the ```readme.md```.

**Comment by Lerke** [comment]
You could install [MSYS2](http://www.msys2.org/) (specifically: coreutils) and add the binaries to your path.
