### ISSUE TITLE
Plugin commands

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#63]
Allow a plugin to add his own commands to the DankTimesBot.
Not sure how this would work considering not all chats might have the same plugins active and commands need to be added to the BotFather to be usefull to the endusers.
Still would be nice if you got it to work.

**Comment by Agadar** [comment]
Commands are currently application-wide, not chat-wide, so this would require some rewriting.

Commands don't need to be added to the BotFather to make them 'useful': the only thing adding commands to the BotFather achieves is auto-completion. Besides, anyone can set the commands of their bot instance via the BotFather.

**Comment by Lerke** [comment]
Plugins may now register /commands with callbacks. See 86d32e101963669feb78f9b8ed54f43b66f4f55b
