### ISSUE TITLE
Danktime and surprise danktime were the same

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#65]
As shown in the image below a danktime and surprise danktime were the same in our chat. We do not have notifications on for danktimes thats why the regular danktime wasn't announced. Our main issue with this is that it's unclear on how we could get the points voor the surprise danktime.

![image](https://user-images.githubusercontent.com/21357422/31167697-36f6b9ac-a8f3-11e7-9857-464c1db25b39.png)

**Comment by Agadar** [comment]
Fixed in 94fafa8.
