### ISSUE TITLE
Fake DankTimes cost points

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#71]
This feature makes sure people wont spam danktimes every minute.
This feature should also have a toggle command to turn it on and off.

**Comment by Agadar** [comment]
Sounds like you've been bamboozled a few times.

**Comment by MaikoKingma** [comment]
No, this would create more opportunities to bamboozle others.

**Comment by Agadar** [comment]
What exactly do you mean by 'fake danktime', then?

**Comment by Agadar** [comment]
Closed due to no response.
