### ISSUE TITLE
Add option to use handicaps

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#73]
As DankTimesBot has been present in a chat for some time, some players might rack up quite a score.
This can have be discouraging to players who entered the chat later, or have a lower score for some other reason. In our chat, the players with high scores sometimes have 10 times the low scoring players' scores.

As an attempt to challenge everyone, also the players that have low scores, a handicap option could help. For example, the three lowest scoring players could have a 1.5x score multiplier. (Just an idea, this constant is open for discussion, or to be set as a parameter by the chat admin)

**Comment by Agadar** [comment]
Implemented in 6be24f1.
