### ISSUE TITLE
If a chat member exits the chat, its score should be wiped 

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#74]
The persistence will also hold a chat member's score if said member has already left the chat. This becomes evident because the username is still on the leaderboard. It would be better if the data for this member was wiped when such event occurs.

**Comment by Agadar** [comment]
Can be implemented using the left_chat_member attribute (see https://core.telegram.org/bots/api#getupdates).

**Comment by Agadar** [comment]
Implemented since 2aaa4ce. Note that this will not work retroactively.
