### ISSUE TITLE
25% of my chat is handicapped

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#76]
This morning I woke up to a disturbing sight. 25% of my telegram chat containing the DankTimesBot is now handicapped. Is this the consequence of an accident? How can I help? Maybe if we band together we can start collecting money to support the victims and their families.

**Comment by teunw** [comment]
Maybe we should make a setting out of this, so we can stop (and speed up) the handicapping of our users.

**Comment by bart-kneepkens** [comment]
This is unacceptable! To make people handicapped is a sin. The players were totally healthy before. Now I have to buy my mom a wheelchair! Are you gonna pay for it?

**Comment by Agadar** [comment]
The intent is to provide players with a sense of pride and accomplishment for unlocking different danktime point multipliers.

As for handicaps, we selected initial values based upon data from version 1.3.2 and other adjustments made to danktime rewards before launch. Among other things, we're looking at average per-player danktime points earn rates on a daily basis, and we'll be making constant adjustments to ensure that players have challenges that are compelling, rewarding, and of course attainable via gameplay.

We appreciate the candid feedback, and the passion the community has put forth around the current topics here on GitHub, the AFK chat and across numerous social media outlets.

Our team will continue to make changes and monitor community feedback and update everyone as soon and as often as we can.
