### ISSUE TITLE
Return a list of people who have not yet scored on the current day

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#83]
I'm not sure if this feature would make hardcore mode easier then intended, but because of the recent update to hardcore mode (which makes it significantly more punishing) I suggest that the players can retrieve a list of of players that have not yet scored on the current day. I would suggest a command like /idiots or the less offensive /dangerzone. You could also use /notscoredplayers but I personally find that to plain.

In the returned message jou have the choice of returning the list with or without the @ before each player name. Of course with @ you notify all users.

Update:  
You could also replace the return message of this command with a message containing only the info about the player who send the command.  
Example:  
Me: /dangerzone  
DankTimesBot: you are in the dangerzone

This would mean that I have not yet scored that day and should score before the end of the day to not lose points.

**Comment by Agadar** [comment]
It does kinda make hardcore mode easier, just for the sake of making it easier. I don't quite see what this would add. If someone cares enough about not getting punished by hardcore mode, then surely they would have scored at least once on a given day, or at the very least recall whether they have scored yet that day?

**Comment by MaikoKingma** [comment]
I'm not sure if I understand your question, but yes people most likely recall have scored yet. Another reason to add this feature might be to just annoy people by notifying them they haven't scored yet. If they remember not scoring that day but keep missing the danktimes.

You might be correct in that this feature makes hardcore mode to easy (it's hardcore mode after all).

**Comment by Agadar** [comment]
Closing for now due to inactivity.
