### ISSUE TITLE
Negative score no longer possible?

### ISSUE THREAD

**Issue by MaikoKingma** [Agadar/DankTimesBot#84]
Is this a bug or feature?

Since the last update it is no longer possible to get a negative score. I've added a picture which shows an example of this bug:  
![danktimesbot bug negative score](https://user-images.githubusercontent.com/21357422/34360376-89d80b0e-ea60-11e7-8278-7067b0a8265b.PNG)

**Comment by Agadar** [comment]
That is most definitely unintended.

**Comment by Lerke** [comment]
Example image doesn't demostrate bug? Are you sure this is a bug?

**Comment by Lerke** [comment]
Tried it out myself. Negative points seem to function.

**Comment by MaikoKingma** [comment]
Tested again and found out I made a mistake the first time.
