### ISSUE TITLE
Port, test, fix and refactor plugin code from stale branches to latest version

### ISSUE THREAD

**Issue by Agadar** [Agadar/DankTimesBot#85]
These branches did not keep up with the latest release, and their status is not entirely clear.

**Comment by Lerke** [comment]
Plugin branch has been updated to 1.6.0. Will need a review from @Agadar though and some testing + fixes before a merge can be considered. See 6f7ccbf3336d81ac16fc41ab5686433f017ec660

**Comment by Agadar** [comment]
When the whole plugin business is done per your set goals, you can make a (WIP) pull request and I'll review the whole thing in one go.

Until then, the one major feedback I have is that the code style (not just indentations, but also variable names etc.) are wildly different from the existing codebase. Consider aligning your code to reflect the existing codestyle.

**Comment by Lerke** [comment]
This is the last issue set for the plugins / 1.6.0 milestone for me. It still requires tests and some fixes here and there, but all core functionality for plugins should now be present in the 1.6.0 branch.

**Comment by Agadar** [comment]
This has been pulled into master and versioned as 1.7.0a1.
