### ISSUE TITLE
Remove possibility of having negative score

### ISSUE THREAD

**Issue by Agadar** [Agadar/DankTimesBot#89]
The only reason one can possibly have a negative score is if they simply want it for trolling purposes: if negative scores weren't possible, then it would be a lot harder to deny others the handicap bonus.

**Comment by Lerke** [comment]
Alternatively: Negative scores could be excluded from the handicap bonus calculation.

**Comment by Agadar** [comment]
I considered that at first, but then I realized that would require more reworking than simply disallowing negative scores, and that negative scores are pointless anyway.

**Comment by Agadar** [comment]
Implemented since 6222f51.
