### ISSUE TITLE
Add a setting that automatically shows the leaderboard after a dank time

### ISSUE THREAD

**Issue by bart-kneepkens** [Agadar/DankTimesBot#9]
Quite often, one of the chat participants will want to see a reward for his effort. Because of this, participants will spam `/leaderboard` after a dank time.

Automatically sending a silent leaderboard would be great. Even more so if it was a setting, so admins can choose for themselves.

**Comment by Agadar** [comment]
Can be combined with automatically sending a silent time declaration (i.e. when it's 13:37 the bot sends a silent message along the lines of 'It's 1337-o-clock!')

**Comment by MaikoKingma** [comment]
Please make sure the leaderboard has a delay so the leaderboard doesn't make it impossible to say a dank time to late.

**Comment by Agadar** [comment]
@MaikoKingma but if the delay is too great, then people will just manually spam `/leaderboard` again. I think it's best if at the exact dank time the silent declaration is made, and exactly one minute later the leaderboard is posted.

**Comment by Agadar** [comment]
Implemented since c9dd1d360e961415a02d14c89c4c87151cdf741a.
