### ISSUE TITLE
Plugin Implementation: Daily / Weekly / Monthly / Yearly Leaderboards

### ISSUE THREAD

**Issue by Lerke** [Agadar/DankTimesBot#91]
Create a plugin to track points over larger timespans. This plugin will have its own repo with its own issues.

**Comment by Lerke** [comment]
Plugin page can be found here: https://github.com/Lerke/DankTimesBot-Plugin-Extended-Leaderboards

**Comment by Agadar** [comment]
Closed, seeing as this is not an issue directly related to DankTimesBot.
