### ISSUE TITLE
Remove danktime notifications if no one scored

### ISSUE THREAD

**Issue by Agadar** [Agadar/DankTimesBot#94]
During the night, there are often (random) dank times to which no one responded. This results in several danktime notifications in a row with no user messages inbetween, which looks rather spammy. These should either be removed by default, or via the setting of an option.

**Comment by MaikoKingma** [comment]
Maybe add an options which allows the players to see how many random danktimes have already happened?

**Comment by Agadar** [comment]
This has been implemented in the 1.7.0 dev branch.
